version: '3.9'
services:
  server-monitor:
    build: .
    container_name: server-monitor
    ports:
      - "8005:8000"
    environment:
      - TZ=Europe/Kiev  # Встановлюємо часовий пояс
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro  # Монтуємо системний час
    restart: unless-stopped